# Generated by Django 4.2.6 on 2023-10-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField()),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='factory.networknode')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factory.networknode')),
                ('products', models.ManyToManyField(to='factory.product')),
            ],
            bases=('factory.networknode',),
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factory.networknode')),
                ('products', models.ManyToManyField(to='factory.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('factory.networknode',),
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('networknode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factory.networknode')),
                ('website', models.URLField()),
                ('products', models.ManyToManyField(to='factory.product')),
            ],
            bases=('factory.networknode',),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
